import random

dicknames = ["Tega has a huge Aaron’s Rod",
             "Tega has a huge Arm",
             "Tega has a huge Baby-Maker",
             "Tega has a huge Blue Vein Meatroll",
             "Tega has a huge Bald-Headed Butler",
             "Tega has a huge Bald-Headed Mouse",
             "Tega has a huge Belly Buster",
             "Tega has a huge Bathtub eel",
             "Tega has a huge Bearded Blood Sausage",
             "Tega has a huge Bird",
             "Tega has a huge Bone",
             "Tega has a huge Baloney",
             "Tega has a huge Banana",
             "Tega has a huge Bat",
             "Tega has a huge Bayonet",
             "Tega has a huge Bean Tosser",
             "Tega has a huge Beef",
             "Tega has a huge Belly Ruffian",
             "Tega has a huge Blade",
             "Tega has a huge Broomstick",
             "Tega has a huge Bum Tickler",
             "Tega has a huge Bush Beater",
             "Tega has a huge Button-Hole Worker",
             "Tega has a huge Cock",
             "Tega has a huge Candle",
             "Tega has a huge Carrot",
             "Tega has a huge Club",
             "Tega has a hugeCrack Haunter",
             "Tega has a huge Cranny Hunter",
             "Tega has a huge Cracksman",
             "Tega has a huge Creamstick",
             "Tega has a huge Culty Gun",
             "Tega has a huge Carnal Stump",
             "Tega has a huge Chicken",
             "Tega has a huge Child-Getter",
             "Tega has a huge Corey",
             "Tega has a huge Crook",
             "Tega has a huge Dick",
             "Tega has a huge Spam Javelin",
             "Tega has a huge Dork",
             "Tega has a huge Dong",
             "Tega has a huge Doniker",
             "Tega has a huge Dingus",
             "Tega has a huge Dipstick",
             "Tega has a huge Dagger",
             "Tega has a huge Dart of Love",
             "Tega has a huge Dearest Member",
             "Tega has a huge Dicky",
             "Tega has a huge Ding-Dong",
             "Tega has a huge Dinger",
             "Tega has a huge Dingle-Dangle",
             "Tega has a huge Dodaddy",
             "Tega has a huge Dolly",
             "Tega has a huge Dooflicker",
             "Tega has a huge Down-Leg",
             "Tega has a huge Dragon",
             "Tega has a huge Eel",
             "Tega has a huge End",
             "Tega has a huge Family-Organ",
             "Tega has a huge Fiddle Bow",
             "Tega has a huge Fish",
             "Tega has a huge Fishing Rod",
             "Tega has a huge Flapper",
             "Tega has a huge Fool-Sticker",
             "Tega has a huge Forefinger",
             "Tega has a huge Fucker",
             "Tega has a huge Foreman",
             "Tega has a huge Gun",
             "Tega has a huge Gut Wrench",
             "Tega has a huge Giggle Stick",
             "Tega has a huge Gadget",
             "Tega has a huge Gardener",
             "Tega has a huge Giggling Pin",
             "Tega has a huge Gooser",
             "Tega has a huge Gravy Maker",
             "Tega has a huge Frinding Tool",
             "Tega has a huge Gristle",
             "Tega has a huge Gut Stick",
             "Tega has a huge Hair Splitter",
             "Tega has a huge Hambone",
             "Tega has a huge Hammer",
             "Tega has a huge Hanging Johnny",
             "Tega has a huge Hoe Handle",
             "Tega has a huge Holy Porker",
             "Tega has a huge Horn",
             "Tega has a huge Hose",
             "Tega has a huge Hot Rod",
             "Tega has a huge Heat-Seeking Moisture Missle",
             "Tega has a huge Hairy Hot Dog",
             "Tega has a huge Jack in the Box",
             "Tega has a huge Jemson",
             "Tega has a huge Jerking Iron",
             "Tega has a huge Jigger",
             "Tega has a huge Jing Jang",
             "Tega has a huge Jockam",
             "Tega has a huge Johnnie",
             "Tega has a huge Johnny One-Eye the Bald-Headed Champ",
             "Tega has a huge Johnson Joint",
             "Tega has a huge Joy Knob",
             "Tega has a huge Joy Prong",
             "Tega has a huge Joy Stick",
             "Tega has a huge Key",
             "Tega has a huge Kidney Cracker",
             "Tega has a huge Kidney Wiper",
             "Tega has a huge Kielbasa",
             "Tega has a huge King Member",
             "Tega has a huge Knob",
             "Tega has a huge Knocker",
             "Tega has a huge Ladies’ Delight",
             "Tega has a huge Ladies’ Lollipop",
             "Tega has a huge Ladies’ Treasure",
             "Tega has a huge Lamp of Life",
             "Tega has a huge Lance",
             "Tega has a huge Life Preserver",
             "Tega has a huge Little Brother",
             "Tega has a huge Little Willie",
             "Tega has a huge Liver Turner",
             "Tega has a huge Live Sausage",
             "Tega has a huge Lizard",
             "Tega has a huge Lob",
             "Tega has a huge Lobcock",
             "Tega has a huge Lobster",
             "Tega has a huge Lollypop",
             "Tega has a huge Long John",
             "Tega has a huge Love Dart",
             "Tega has a huge Love Gun",
             "Tega has a huge Love Muscle",
             "Tega has a huge Lung Disturber",
             "Tega has a huge Mad Mick",
             "Tega has a huge Magic Wand",
             "Tega has a huge Man-Root",
             "Tega has a huge Marrow Bone",
             "Tega has a huge Master John Thursday",
             "Tega has a huge Master of Ceremonies",
             "Tega has a huge Meat Hook",
             "Tega has a huge Meat Whistle",
             "Tega has a huge Member",
             "Tega has a huge Merrymaker",
             "Tega has a huge Middle Leg",
             "Tega has a huge Milkman",
             "Tega has a huge Mister Goodwrench",
             "Tega has a huge Mister Tom",
             "Tega has a huge Mouse",
             "Tega has a huge Muscle",
             "Tega has a huge Mutton Dagger",
             "Tega has a huge Body Captain",
             "Tega has a huge Natural Scythe",
             "Tega has a huge Needle",
             "Tega has a huge Nimrod",
             "Tega has a huge Nippy",
             "Tega has a huge Noodle",
             "Tega has a huge Noony",
             "Tega has a huge Old Blind Bob",
             "Tega has a huge One-Eyed Milkman",
             "Tega has a huge One-Eyed Trouser Trout",
             "Tega has a huge One-Eyed Night Crawler in the Turtle-Neck Sweater",
             "Tega has a huge One-Eyed Wonder Worm",
             "Tega has a huge Pant Muscle",
             "Tega has a huge Pecker",
             "Tega has a huge Pee-Pee",
             "Tega has a huge Pen",
             "Tega has a huge Pencil",
             "Tega has a huge Pendulum",
             "Tega has a huge Perch",
             "Tega has a huge Peter",
             "Tega has a huge Piccolo",
             "Tega has a huge Picklock",
             "Tega has a huge Pikestaff",
             "Tega has a huge Pile Driver",
             "Tega has a huge Pin",
             "Tega has a huge Pink Pencil",
             "Tega has a huge Pipe",
             "Tega has a huge Pisser",
             "Tega has a huge Pistol",
             "Tega has a huge Plugtail",
             "Tega has a huge Pocket Piccolo",
             "Tega has a huge Pocket Rocket",
             "Tega has a huge Pointer",
             "Tega has a huge Poker",
             "Tega has a huge Pole",
             "Tega has a huge Pork",
             "Tega has a huge Pork Sword",
             "Tega has a huge Post",
             "Tega has a huge Prick",
             "Tega has a huge Pride & Joy",
             "Tega has a huge Prong",
             "Tega has a huge Pud",
             "Tega has a huge Pudding",
             "Tega has a huge Pump Handle",
             "Tega has a huge Purple-Helmeted Warrior of Love",
             "Tega has a huge Pup",
             "Tega has a huge Putz",
             "Tega has a huge Quickening Peg",
             "Tega has a huge Quimstake",
             "Tega has a huge Ram",
             "Tega has a huge Ramrod",
             "Tega has a huge Raw Meat",
             "Tega has a huge Reamer",
             "Tega has a huge Red Cap",
             "Tega has a huge Rod",
             "Tega has a huge Rod of Love",
             "Tega has a huge Rolling Pin",
             "Tega has a huge Root",
             "Tega has a huge Rudder",
             "Tega has a huge Rupert",
             "Tega has a huge St. Peter",
             "Tega has a huge Russel the Wonder",
             "Tega has a huge Muscle",
             "Tega has a huge Salami",
             "Tega has a huge Sausage",
             "Tega has a huge Sceptre",
             "Tega has a huge Schlong",
             "Tega has a huge Sexing Piece",
             "Tega has a huge Shaft",
             "Tega has a huge Shmock",
             "Tega has a huge Short Arm",
             "Tega has a huge Sove Devil",
             "Tega has a huge Shvontz",
             "Tega has a huge Silent Flute",
             "Tega has a huge Skin Flute",
             "Tega has a huge Snake",
             "Tega has a huge Spigot",
             "Tega has a huge Spindle",
             "Tega has a huge Split-Rump",
             "Tega has a huge Spout",
             "Tega has a huge Staff",
             "Tega has a huge Steaming Hot Kanga",
             "Tega has a huge Stem",
             "Tega has a huge Stick",
             "Tega has a huge Sting",
             "Tega has a huge Stump",
             "Tega has a huge Sugar Stick",
             "Tega has a huge Sword",
             "Tega has a huge Tail Pin",
             "Tega has a huge Tally-Whacker",
             "Tega has a huge Tassel",
             "Tega has a huge Tent Pig",
             "Tega has a huge Thing",
             "Tega has a huge Third Leg",
             "Tega has a huge Thistle",
             "Tega has a huge Throbber",
             "Tega has a huge Throbbing Python of Love",
             "Tega has a huge Tickle-Gizzard",
             "Tega has a huge Tickler",
             "Tega has a huge Tong",
             "Tega has a huge Tool",
             "Tega has a huge Torch or Cupid",
             "Tega has a huge Toy",
             "Tega has a huge Trap-Stick",
             "Tega has a huge Trouser Anaconda",
             "Tega has a huge Tube Steak",
             "Tega has a huge Uncle Dick",
             "Tega has a huge Vomiting Cobra",
             "Tega has a huge Wand",
             "Tega has a huge Wang",
             "Tega has a huge Wazoo",
             "Tega has a huge Weapon",
             "Tega has a huge Wedge",
             "Tega has a huge Weenie",
             "Tega has a huge Whacker",
             "Tega has a huge Whip",
             "Tega has a huge Whistle",
             "Tega has a huge Whore-Pipe",
             "Tega has a huge Wick",
             "Tega has a huge Willie",
             "Tega has a huge Wingle",
             "Tega has a huge Wire",
             "Tega has a huge Worm",
             "Tega has a huge Yang",
             "Tega has a huge Yard",
             "Tega has a huge Yosh",
             "Tega has a huge Zubrick",
             "Tegas got Basket for Days",
             "Tegas Donkey-Rigged",
             "Tegas Double-Shung",
             "Tegas Hung Like a Bull",
             "Tegas got Miracle Meat",
             "Tegas Timbered",
             "Tegas got Tons of Basket",
             "Tegas got Tons of Meat",
             "Tegas Well-Favored by Nature",
             "Tegas Well Hung",
             "Tegas got Yard",
             "Tegas dick is so big, there’s still snow on it in the summertime",
             "Tegas dick is so big, he went to The Viper Room and his dick got right in. He had to stand and argue with the doorman.",
             "Tegas dick is so big, He has to call it Mr. Dick in front of company.",
             "Tegas dick is so big, it wont return Spielbergs calls.",
             "Tegas dick is so big, it graduated a year ahead of him from high school.",
             "Tegas dick has an elevator and a lobby.",
             "Tegas dick has better credit than he does.",
             "Tegas dick is so big, clowns climb out of it when he cums.",
             "Tegas dick is so big, it was overthrown by a military coup. Its now known as the Democratic Republic of Tegas Dick.",
             "Tegas dick is so big, it has casters.",
             "Tegas dick is so big, hes already fucking a girl tomorrow.",
             "Tegas dick is so big, ships use it to find their way into the harbour.",
             "Tegas dick is so big, there was once a movie called Godzilla vs. Tegas Dick.",
             "Tegas dick is so big, it lives next door to him.",
             "Tegas dick is so big, he entered it in a big-dick contest and it came in first, second, and third.",
             "Tegas dick is so big, it votes.",
             "Tegas dick is a better dresser than he is.",
             "Tegas dick is so big, it has a three-picture deal.",
             "Tegas dick is so big that the head of it has only seen Tegas balls in pictures.",
             "No matter where he goes, Tegas dick always gets there first.",
             "Tegas dick takes longer lunches than he does.",
             "Tegas dick contributed fifty thousand dollars to the Democratic National Committee.",
             "Tegas dick was once the ambassador to China.",
             "Tegas dick is so big, its gone condo.",
             "Tegas dick is so big, he uses the Eiffel Tower as a French tickler.",
             "Its so big, when it rains the head of Tegas dick doesnt get wet.",
             "Tegas dick is so big, he could wear it as a tie if he wasnt so afraid of getting a hard-on and killing him.",
             "Tegas dick is so big, he has to use an elastic zipper.",
             "Tegas dick is so big, it has feet.",
             "Tegas dick is so big, a homeless family lives underneath it.",
             "Tegas dick is so big, it takes four fat women and a team of Clydesdales to jack him off.",
             "Tegas dick is so big, they use the bullet train to test Tegas condoms.",
             "Tegas dick is so big, it has investors.",
             "Tegas dick is so big, it seats six.",
             "Tegas dick is so big, he uses a hula hoop as a cock ring.",
             "Tegas dick is so big, he uses it at parties as a limbo pole.",
             "Tegas dick is so big, King Kong is going to crawl up it in the next remake.",
             "Tegas dick is so big, it has an opening act.",
             "Tegas dick is so big he can fuck an elevator shaft.",
             "Tegas dick is so big, it has its own Wheaties box.",
             "Tegas dick is so big, he has to cook it breakfast in the mornings.",
             "Tegas dick is so big, the city had to carve a hole in the middle of it so cars could get through.",
             "Tegas dick is so big, every time he gets hard he causes a solar eclipse.",
             "Tegas dick is so big, it only plays arenas.",
             "If you cut Tegas dick in two, you can tell how old he is.",
             "Tegas dick is so big, it needs an airplane warning light.",
             "Tegas dick is so big that were all a part of it, and its all a part of us.",
             "Tegas dick is so big, he can never sit in the front row.",
             "Tegas dick is so big, it has its own dick. And even Tegas dicks dick is bigger than your dick.",
             "Tegas dick is so big, you cant blow him without a ladder.",
             "Tegas dick is so big, it only does one show a night.",
             "Tegas dick is so big, you can ski down it.",
             "Tegas dick is so big, it has elbows.",
             "Tegas dick is so big, he has to check it as luggage when he flies.",
             "Tegas dick is so big, it has a personal trainer.",
             "Tegas dick is so big, that right now its in the other room fixing us drinks.",
             "Tegas dick is so big, it has a retractable dome.",
             "Tegas dick is so big, it has stairs up the center like the Statue of Liberty.",
             "Tegas dick is so big, its against the law to fuck him without protective headgear.",
             "Tegas dick is so big, he could fuck a tuba.",
             "Tegas dick is so big, Stephen Hawking has a theory about it.",
             "Tegas dick is so big, it has its own gravity",
             "NASA once launched a space probe to search for the tip of Tegas dick.",
             "Tegas dick is so big, its impossible to see all of it without a satellite.",
             "The inside of Tegas dick contains billions and billions of stars.",
             "Tegas dick is so big, it has a spine.",
             "Tegas dick is so big, it has a basement.",
             "Tegas dick is so big, movie theatres now serve popcorn in small, medium, large, and Tegas Dick.",
             "Tegas dick is more muscular than he is.",
             "Tegas dick is so big it has cable.",
             "Tegas dick is so big, it violates seventeen zoning laws.",
             "Tegas dick is so big, it has its own page in the Sierra Club calendar.",
             "Tegas dick is so big, it has a fifty-yard line.",
             "Tegas dick is so big, he was once in Ohio and got a blow job in Tennessee.",
             "Tegas dick is so big, Las Vegas casinos fly it into town for free.",
             "Tegas dick is so big, he can braid it.",
             "Tegas dick is so big, that when its Eastern Standard Time at the tip, its Central Mountain Time at Tegas balls.",
             "Tegas dick is so big, he can sit on it.",
             "Tegas dick is so big, it can chew gum.",
             "Tegas dick is so big, it only tips with hundreds.",
             "Tegas dick is so big, the Carnegie Deli named a sandwich after it. Actually, two sandwiches.",
             "Tegas dick is so big, the city was going to build a statue of it but they ran out of cement.",
             "Tegas dick is so big, Michael Jackson wants to build an amusement park on it.",
             "Tegas dick is so big, when he gets hard his eyebrows get pulled down to his neck.",
             "Tegas dick is so big, youre standing on it.",
             "Tegas dick is so big, it only comes into work when it feels like it.",
             "Tegas dick is so big, it plays golf with the president.",
             "Tegas dick is so big, it charges money for its autograph.",
             "Tegas dick is so big, it has an agent.",
             "Tegas dicks people will call your people. Lets have lunch with Tegas dick.",
             "Tegas dick is so big, its right behind you.",
             "Tegas dick is so big, it has handlebars.",
             "Tegas dick is so big, it only does one show per night.",
             "Tegas dick is so big, he can only drive convertibles.",
             "Tegas dick is so big, when he gets a hard on half of his body goes numb.",
             "Tegas dick is so big, when he gets a hard on it hits him in the face.",
             "Tegas dick is so big, it put the president on hold for 20 minutes.",
             "Tegas dick is so big, MTVs Cribs dedicated a whole episode to it.",
             "Tegas dick is so big, he can drive alone and still use the carpool lane.",
             "Tegas dick is so big, it got into Guinness by being the first Mr. Olympia with no arms.",
             "Tegas dick is so big, it seats 10,000",
             "Tegas dick is so big, it fired Alan Sugar",
             "Tegas dick is so big, it was Vin Diesels stunt double in XXX",
             "Tegas dick is so big, he live in its guest room.",
             "Tegas dick is so big, it has its own cleaning crew.",
             "Tegas dick is so big, Firemen slide down it."]


print (random.choice(dicknames))
